apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
    - name: my-container
      image: busybox
      args: [ "tail", "-f", "/dev/null" ]
      volumeMounts:
        - name: configmap-volume
          mountPath: /etc/config # container 안의 경로에 configmap 을 마운트
  volumes:
    - name: configmap-volume
      configMap:
        name: start-k8s